### ISSUE TITLE
[Bug]: Error opening minecraft

### ISSUE THREAD

**Issue by gabrielpoa** [Cheos137/ArmorpointsPlusplus#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using minecraft 1.18 with ATLauncher and the mod Armorpoints++, when I open the minecraft the error appears in the log: Exception in thread "main" java.lang.IllegalArgumentException: forge-1.18-2.1.3: Version string does not start with a number

### Version

Other (this list is not up to date - again...)

### Version

forge-1.18-2.1.3

### To Reproduce

Install mod
open minecraft

### Relevant Log / Crash-Report Output

```shell
[07/12/2021 10:48:24 AM] Exception in thread "main" java.lang.IllegalArgumentException: forge-1.18-2.1.3: Version string does not start with a number
[07/12/2021 10:48:24 AM] 	at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1005)
[07/12/2021 10:48:24 AM] 	at java.base/java.lang.module.ModuleDescriptor$Version.parse(ModuleDescriptor.java:1090)
[07/12/2021 10:48:24 AM] 	at java.base/java.lang.module.ModuleDescriptor$Builder.version(ModuleDescriptor.java:2062)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/fmlloader@1.18-38.0.15/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.descriptor(ModJarMetadata.java:67)
[07/12/2021 10:48:24 AM] 	at cpw.mods.securejarhandler@0.9.54/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:47)
[07/12/2021 10:48:24 AM] 	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
[07/12/2021 10:48:24 AM] 	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.JarModuleFinder.lambda$new$0(JarModuleFinder.java:28)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[07/12/2021 10:48:24 AM] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[07/12/2021 10:48:24 AM] 	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
[07/12/2021 10:48:24 AM] 	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[07/12/2021 10:48:24 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[07/12/2021 10:48:24 AM] 	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

**Comment by gabrielpoa** [comment]
bug already documented

**Comment by Cheos137** [comment]
Is the version you downloaded more than 12 hours old? If yes, please re-download the v2.1.3 build for 1.18, that should fix it.
Can you please confirm that it works/doesn't work once you tested it again? Thank you!

**Comment by gabrielpoa** [comment]
I have version v2.1.3. I've already removed the mod, downloaded it again and reinstalled it and the error still persists. Please generate a new version and make it available in Forge, the one there is before the fix.

**Comment by Cheos137** [comment]
I gotta blame curseforge there for not properly updating the jar (even though i deleted and reuploaded it...)
same version tagged as v2.1.4 will be up in a few minutes

**Comment by Cheos137** [comment]
2.1.4 is now approved and available: https://www.curseforge.com/minecraft/mc-mods/armorpoints/files/3556216
