### ISSUE TITLE
[Bug]: AP++ weird compat bug with another mod. 

### ISSUE THREAD

**Issue by Zelioth** [Cheos137/ArmorpointsPlusplus#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Installing AP++ Update 3.1.0 seems to cause crash on startup with this error 

Mixin apply failed armorpointspp.mixins.json:PlayerTabOverlayMixin -> net.minecraft.client.gui.components.PlayerTabOverlay: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field f_244278_ was not located in the target class net.minecraft.client.gui.components.PlayerTabOverlay. Using refmap armorpointspp.refmap.json

### Version

3.1.x for Minecraft Forge 1.19.2+

### Version

forge - 43.2.10

### To Reproduce

install the mod 
start the pack
potato

### Expexted Behavior

to work 

### Relevant Log / Crash-Report Output

```shell
https://gist.github.com/Zelioth/39169a57bb4f6b7417eb22c786f3deff
```

**Comment by Cheos137** [comment]
try re-downloading the mod - this has been fixed previously (#75) and available builds have been replaced with a fixed version

**Comment by Zelioth** [comment]
Re-downloading and using later versions of forge didn't fix it. The mod still crashes the client on startup for version 3.1.0. Deleting everything todo with the mod and re-downloading didn't seem to fix anything.
